some ui things
so-sc/Sankalp pull request #4
Opened 2023-11-21 11:00 UTC by srajankumar

2023-11-22 00:30 UTC, dev-shetty commented on web/client/src/app/hackathon/page.tsx
> +      </h3>
There is H1 and H2 component, you can override styles on that

2023-11-22 00:32 UTC, dev-shetty requested changes
I have added `.prettier.rc` file just make sure you again save the edited files so the semincolons and all which were added now get removed.

Also add the screenshot of the pages UI you changed will help a lot.

2023-11-22 02:10 UTC, srajankumar commented
![image](https://github.com/so-sc/Sankalp/assets/103196610/a8163a5f-1755-4612-ba17-2928775ffaaf)

![image](https://github.com/so-sc/Sankalp/assets/103196610/6d5e78fe-030b-49ec-b900-4032ef92f3ca)

![image](https://github.com/so-sc/Sankalp/assets/103196610/0f8fa2ba-b87f-4db5-ac48-20128cb7c133)

![image](https://github.com/so-sc/Sankalp/assets/103196610/6bdaadb4-736c-4ca8-b008-e37be71c67e1)

![image](https://github.com/so-sc/Sankalp/assets/103196610/0a530fe0-c156-4d0d-8a80-14cb44692f2f)

2023-11-22 02:11 UTC, srajankumar commented
snapshots of the changes

2023-11-24 00:50 UTC, dev-shetty commented
@srajankumar this space seems too much on PC

![image](https://github.com/so-sc/Sankalp/assets/89470104/fe6fcf20-acf5-4373-89fb-3c0bf5754a97)

Maybe it looks good on mobile but it is just empty space with no use, try to reduce it

2023-11-24 04:15 UTC, srajankumar commented
> @srajankumar this space seems too much on PC (Above the title Codeblaze, even in Dashboard I fell)
> 
> ![image](https://user-images.githubusercontent.com/89470104/285328606-fe6fcf20-acf5-4373-89fb-3c0bf5754a97.png)
> 
> Maybe it looks good on mobile but it is just empty space with no use, try to reduce it

Decreased padding 

![image](https://github.com/so-sc/Sankalp/assets/103196610/85b9843a-36e9-4027-bd05-aca4401b473a)

2023-11-24 14:04 UTC, dev-shetty approved these changes
LGTM ✅

2023-11-24 14:04 UTC, merged